"""
ZivaBI — General Ledger ORM models (GL Engine #1).

Tables:
    journal_entries   — GL journal header: date, description, source, status.
    journal_lines     — Double-entry lines: GL account, debit/credit, dimensions.

Design notes:
- Tenant-scoped via tenant_id FK, following the same pattern as all other modules.
- Dimensions per line are stored as JSONB: {str(dimension_id): str(dimension_value_id)}.
  This is simpler than a child join table and fully queryable in PostgreSQL.
- environment column is NOT included — test/live isolation is enforced by tenant_id
  (test tenants have distinct IDs); adding an environment column would be redundant.
- Reversal fields (reversed_by_entry_id / reverses_entry_id) are schema-ready but
  no reversal logic is built in this brief — corrections via reversing entries come later.
- reference_number is unique per tenant (e.g. "JE-2026-000001"), generated by the
  posting service using a tenant-scoped count-based sequence.
- status: 'DRAFT' | 'POSTED' | 'REVERSED'. POSTED entries are immutable.
- The service flushes only; the router-level get_db() commits on success.
"""

import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import (
    DateTime,
    Date,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
    Index,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class JournalEntry(Base):
    """
    GL journal header.

    Every balanced set of debit/credit lines must have one JournalEntry header.
    Once POSTED, the entry is immutable — corrections require a reversing entry.

    source values (free string set by the calling module):
        'manual'    — manual journal entered via UI
        'expense'   — posted by the expense retirement module
        'ap'        — accounts payable
        'fx'        — FX revaluation
        'year_end'  — year-end retained-earnings roll-forward

    reference_number format: "JE-{YYYY}-{000001}" — unique per tenant,
    generated at post time by counting existing entries for this tenant.

    Reversal links (schema-ready, logic is a later brief):
        reverses_entry_id       — if this entry reverses another, points to it
        reversed_by_entry_id    — if another entry reversed this one, points to it
    """

    __tablename__ = "journal_entries"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    entry_date: Mapped[date] = mapped_column(Date, nullable=False)
    description: Mapped[str] = mapped_column(String(500), nullable=False)
    source: Mapped[str] = mapped_column(String(50), nullable=False)
    source_reference: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    reference_number: Mapped[str] = mapped_column(String(30), nullable=False)

    # 'DRAFT' | 'POSTED' | 'REVERSED'
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="POSTED")

    # Reversal links — schema-ready; reversal logic is a future brief.
    reverses_entry_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("journal_entries.id", ondelete="SET NULL"),
        nullable=True,
    )
    reversed_by_entry_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("journal_entries.id", ondelete="SET NULL"),
        nullable=True,
    )

    created_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    posted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    lines: Mapped[list["JournalLine"]] = relationship(
        "JournalLine",
        back_populates="entry",
        cascade="all, delete-orphan",
        order_by="JournalLine.line_number",
    )

    __table_args__ = (
        # Enforce unique human-readable reference numbers per tenant.
        UniqueConstraint("tenant_id", "reference_number", name="uq_je_tenant_ref"),
        # Fast lookups by date for period reporting.
        Index("ix_je_tenant_date", "tenant_id", "entry_date"),
    )


class JournalLine(Base):
    """
    One side of a double-entry line within a JournalEntry.

    Invariants enforced by the posting service (not the DB — application-layer rules):
      - Exactly one of debit/credit > 0; the other must be 0.
      - No negative amounts.
      - Across all lines: Σ debit == Σ credit.

    dimensions: JSONB dict mapping {str(dimension_id): str(dimension_value_id)}.
    Chosen over a child join table (journal_line_dimensions) because:
      - No extra table/join for v1 reporting.
      - JSONB is queryable in PostgreSQL (e.g. `@>` for filtering by dimension value).
      - Adding a child table later is a simple additive migration if needed.
    """

    __tablename__ = "journal_lines"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    journal_entry_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("journal_entries.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    gl_account_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("chart_of_accounts.id"),  # no CASCADE — preserve lines even if GL archived
        nullable=False,
        index=True,
    )
    debit: Mapped[Decimal] = mapped_column(
        Numeric(18, 2), nullable=False, default=Decimal("0")
    )
    credit: Mapped[Decimal] = mapped_column(
        Numeric(18, 2), nullable=False, default=Decimal("0")
    )
    description: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    line_number: Mapped[int] = mapped_column(Integer, nullable=False)

    # Dimension values per line: {str(dimension_id): str(dimension_value_id)}
    dimensions: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)

    # Optional bank account tag for reconciliation/reporting. Nullable — existing
    # lines and any posting that doesn't specify a bank account are unaffected.
    # SET NULL on delete so removing a bank account doesn't orphan lines.
    # Reconciliation tooling that uses this tag is a FUTURE module.
    bank_account_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("bank_accounts.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    entry: Mapped["JournalEntry"] = relationship("JournalEntry", back_populates="lines")
