"""create_expense_tables

Revision ID: 87e40b59d47f
Revises: 72a96af108c3
Create Date: 2026-05-18 05:03:28.572577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87e40b59d47f'
down_revision: Union[str, None] = '72a96af108c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=100), nullable=True),
    sa.Column('employee_function', sa.String(length=255), nullable=True),
    sa.Column('report_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_reports_employee_id'), 'expense_reports', ['employee_id'], unique=False)
    op.create_index(op.f('ix_expense_reports_report_number'), 'expense_reports', ['report_number'], unique=False)
    op.create_index(op.f('ix_expense_reports_tenant_id'), 'expense_reports', ['tenant_id'], unique=False)
    op.create_table('expense_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('pl_group', sa.String(length=50), nullable=True),
    sa.Column('gl_account', sa.String(length=255), nullable=False),
    sa.Column('io_dimension', sa.String(length=255), nullable=True),
    sa.Column('cost_center', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_lines_report_id'), 'expense_lines', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_lines_report_id'), table_name='expense_lines')
    op.drop_table('expense_lines')
    op.drop_index(op.f('ix_expense_reports_tenant_id'), table_name='expense_reports')
    op.drop_index(op.f('ix_expense_reports_report_number'), table_name='expense_reports')
    op.drop_index(op.f('ix_expense_reports_employee_id'), table_name='expense_reports')
    op.drop_table('expense_reports')
    # ### end Alembic commands ###
