"""
ZivaBI API — application settings.

All configuration is read from environment variables (or a .env file for local dev).
In production (Render), environment variables are injected via the Render dashboard —
nothing sensitive is ever stored in this file or committed to GitHub.

ALLOWED_ORIGINS accepts either a JSON array string or a comma-separated list so that
both local .env files and Render's single-value env var format work without changes.

Add new config fields here as modules are built; keep secrets out of default values.
"""

import json
from typing import Any

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # ── Database ──────────────────────────────────────────────────────────────
    # Render injects DATABASE_URL automatically from the linked PostgreSQL service.
    # Local dev: set this in backend/.env (see .env.example).
    database_url: str = "postgresql+asyncpg://postgres:postgres@localhost:5432/ziva_bi"

    # ── JWT ───────────────────────────────────────────────────────────────────
    # SECRET_KEY is auto-generated by Render (generateValue: true in render.yaml).
    # Never use the default below in production.
    secret_key: str = "change-me-in-production"
    algorithm: str = "HS256"
    access_token_expire_minutes: int = 30
    refresh_token_expire_days: int = 7

    # ── Cloudflare R2 (file storage) ──────────────────────────────────────────
    r2_account_id: str = ""
    r2_access_key_id: str = ""
    r2_secret_access_key: str = ""
    r2_bucket_name: str = ""

    # ── CORS ──────────────────────────────────────────────────────────────────
    # Accepts: JSON array '["https://a.com","https://b.com"]'
    #       or comma-separated 'https://a.com,https://b.com'
    #       or a single URL 'https://a.com'
    allowed_origins: list[str] = ["http://localhost:3000"]

    # ── SMTP (email notifications) ────────────────────────────────────────────
    # If SMTP_HOST / SMTP_USER / SMTP_PASSWORD are not set, rejection emails
    # are logged to the console instead of sent — safe for local dev.
    smtp_host: str = ""
    smtp_port: int = 587
    smtp_user: str = ""
    smtp_password: str = ""
    smtp_from_email: str = ""

    # ── App ───────────────────────────────────────────────────────────────────
    app_name: str = "ZivaBI"
    debug: bool = False

    @field_validator("allowed_origins", mode="before")
    @classmethod
    def parse_allowed_origins(cls, v: Any) -> list[str]:
        """Parse ALLOWED_ORIGINS from env regardless of whether it arrives as a
        JSON array string, a comma-separated string, or already a list."""
        if isinstance(v, list):
            return v
        if isinstance(v, str):
            stripped = v.strip()
            if stripped.startswith("["):
                return json.loads(stripped)
            return [origin.strip() for origin in stripped.split(",") if origin.strip()]
        return v


settings = Settings()
