"""
ZivaBI API — application settings.

All configuration is read from environment variables (or a .env file for local dev).
In production (Render), environment variables are injected via the Render dashboard —
nothing sensitive is ever stored in this file or committed to GitHub.

ALLOWED_ORIGINS accepts either a JSON array string or a comma-separated list so that
both local .env files and Render's single-value env var format work without changes.

Add new config fields here as modules are built; keep secrets out of default values.
"""

import json
from typing import Any

from pydantic import AliasChoices, Field, computed_field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        populate_by_name=True,   # allow field access by its own name, not just alias
    )

    # ── Database ──────────────────────────────────────────────────────────────
    # Render injects DATABASE_URL automatically from the linked PostgreSQL service.
    # Local dev: set this in backend/.env (see .env.example).
    database_url: str = "postgresql+asyncpg://postgres:postgres@localhost:5432/ziva_dev"

    # ── JWT ───────────────────────────────────────────────────────────────────
    # SECRET_KEY is auto-generated by Render (generateValue: true in render.yaml).
    # Never use the default below in production.
    secret_key: str = "change-me-in-production"
    algorithm: str = "HS256"
    access_token_expire_minutes: int = 480
    refresh_token_expire_days: int = 7

    # ── Cloudflare R2 (file storage — reserved for future use) ───────────────
    r2_account_id: str = ""
    r2_access_key_id: str = ""
    r2_secret_access_key: str = ""
    r2_bucket_name: str = ""

    # ── Supabase Storage (M6 — document attachments) ──────────────────────────
    # Service-role key grants full bucket access — keep secret, never expose to frontend.
    supabase_url: str = ""
    supabase_service_role_key: str = ""
    supabase_bucket: str = "documents"

    # ── CORS ──────────────────────────────────────────────────────────────────
    # Accepts: JSON array '["https://a.com","https://b.com"]'
    #       or comma-separated 'https://a.com,https://b.com'
    #       or a single URL 'https://a.com'
    #
    # NOTE: stored as `str` so that pydantic-settings v2 does not attempt to
    # JSON-parse the value at source level (which fails for plain URLs).
    # The `allowed_origins` computed property does the actual parsing.
    # validation_alias maps this field to the ALLOWED_ORIGINS env var.
    allowed_origins_raw: str = Field(
        default="http://localhost:3000",
        validation_alias=AliasChoices("ALLOWED_ORIGINS", "allowed_origins_raw"),
    )

    # ── Email (P2 — Resend) ───────────────────────────────────────────────────
    # Set RESEND_API_KEY in the Render dashboard (or backend/.env for local dev).
    # When not set, all email calls fall back to a console simulation log —
    # safe for local dev without any additional configuration.
    resend_api_key: str = ""
    # "From" header used in all outbound emails.
    # Production: use a verified Resend domain, e.g. "Ziva BI <noreply@mail.zivafinance.com>".
    # Default works immediately via Resend's shared domain (limits: 100 emails/day).
    email_from: str = "Ziva BI <onboarding@resend.dev>"

    # ── Frontend URL (used in email links) ────────────────────────────────────
    frontend_url: str = "http://localhost:3000"

    # ── App ───────────────────────────────────────────────────────────────────
    app_name: str = "ZivaBI"
    debug: bool = False

    # ── Platform owner ────────────────────────────────────────────────────────
    # UUID of the Ziva BI platform owner. When set, this user's impersonation
    # sessions in live environments are unrestricted (no sensitive field masking).
    # If unset, all super admins are treated as non-owner (restricted in live).
    owner_user_id: str | None = None

    @computed_field  # type: ignore[misc]
    @property
    def allowed_origins(self) -> list[str]:
        """Parse ALLOWED_ORIGINS into a list regardless of input format.

        Accepts:
          - JSON array string: '["https://a.com","https://b.com"]'
          - Comma-separated:   'https://a.com,https://b.com'
          - Single URL:        'https://a.com'

        Using a computed_field (rather than a field_validator on a list[str]
        field) prevents pydantic-settings v2 from attempting JSON-parsing at
        the source level before our own parsing logic runs.
        """
        v: Any = self.allowed_origins_raw
        if isinstance(v, list):
            return v
        if isinstance(v, str):
            stripped = v.strip()
            if stripped.startswith("["):
                return json.loads(stripped)
            return [origin.strip() for origin in stripped.split(",") if origin.strip()]
        return [str(v)]


settings = Settings()
