"""
PRAD API — application settings.

All configuration is read from environment variables (or a .env file for local dev).
In production (Render), environment variables are injected via the Render dashboard —
nothing sensitive is ever stored in this file or committed to GitHub.

ALLOWED_ORIGINS accepts either a JSON array string or a comma-separated list so that
both local .env files and Render's single-value env var format work without changes.

Add new config fields here as modules are built; keep secrets out of default values.
"""

import json
from typing import Any

from pydantic import AliasChoices, Field, computed_field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        populate_by_name=True,   # allow field access by its own name, not just alias
    )

    # ── Database ──────────────────────────────────────────────────────────────
    # Render injects DATABASE_URL automatically from the linked PostgreSQL service.
    # Local dev: set this in backend/.env (see .env.example).
    database_url: str = "postgresql+asyncpg://postgres:postgres@localhost:5432/ziva_dev"

    # ── JWT ───────────────────────────────────────────────────────────────────
    # SECRET_KEY is auto-generated by Render (generateValue: true in render.yaml).
    # Never use the default below in production.
    secret_key: str = "change-me-in-production"
    algorithm: str = "HS256"
    access_token_expire_minutes: int = 480
    refresh_token_expire_days: int = 7

    # ── Cloudflare R2 (file storage — reserved for future use) ───────────────
    r2_account_id: str = ""
    r2_access_key_id: str = ""
    r2_secret_access_key: str = ""
    r2_bucket_name: str = ""

    # ── Supabase Storage (M6 — document attachments) ──────────────────────────
    # Service-role key grants full bucket access — keep secret, never expose to frontend.
    supabase_url: str = ""
    supabase_service_role_key: str = ""
    supabase_bucket: str = "documents"

    # ── CORS ──────────────────────────────────────────────────────────────────
    # Accepts: JSON array '["https://a.com","https://b.com"]'
    #       or comma-separated 'https://a.com,https://b.com'
    #       or a single URL 'https://a.com'
    #
    # NOTE: stored as `str` so that pydantic-settings v2 does not attempt to
    # JSON-parse the value at source level (which fails for plain URLs).
    # The `allowed_origins` computed property does the actual parsing.
    # validation_alias maps this field to the ALLOWED_ORIGINS env var.
    allowed_origins_raw: str = Field(
        default="http://localhost:3000",
        validation_alias=AliasChoices("ALLOWED_ORIGINS", "allowed_origins_raw"),
    )

    # ── Email (P2 — Resend) ───────────────────────────────────────────────────
    # Set RESEND_API_KEY in the Render dashboard (or backend/.env for local dev).
    # When not set, all email calls fall back to a console simulation log —
    # safe for local dev without any additional configuration.
    resend_api_key: str = ""
    # "From" header used in all outbound emails.
    # Production: use a verified Resend domain, e.g. "PRAD <noreply@mail.zivafinance.com>".
    # Default works immediately via Resend's shared domain (limits: 100 emails/day).
    email_from: str = "PRAD <onboarding@resend.dev>"

    # ── Anthropic AI (M10 — OCR & AI Engine) ─────────────────────────────────
    # Set ANTHROPIC_API_KEY in Render dashboard or backend/.env.
    # If blank, the OCR endpoint returns HTTP 501 (not configured) instead of crashing.
    anthropic_api_key: str = ""

    # ── Frontend URL (used in email links) ────────────────────────────────────
    frontend_url: str = "http://localhost:3000"

    # ── App ───────────────────────────────────────────────────────────────────
    app_name: str = "PRAD"
    debug: bool = False

    # ── Environment ───────────────────────────────────────────────────────────
    # Controls env-sensitive behaviour: httpOnly cookie Secure attr,
    # WebAuthn RP ID, etc. Set ENVIRONMENT=production in the Render dashboard.
    # Default: "development" so local dev works with no extra config.
    environment: str = "development"

    # ── Cookie domain ─────────────────────────────────────────────────────────
    # Domain attribute for the httpOnly refresh-token cookie (ziva_rt).
    # Leave unset (None) until a custom domain is live in DNS — the cookie
    # becomes host-only for the actual serving origin, which works correctly
    # on Render's *.onrender.com domain.
    # Set COOKIE_DOMAIN=.yourdomain.com in Render once the custom domain
    # is configured and DNS-verified (Phase 3+ / custom domain cutover).
    cookie_domain: str | None = None

    # ── WebAuthn (Phase 3) ────────────────────────────────────────────────────
    # rpId must be a registrable-domain suffix of the actual frontend origin.
    # Default is "localhost" (works for local dev without any config).
    # Set WEBAUTHN_RP_ID in Render to match the actual serving domain:
    #   today  → "ziva-bi-frontend.onrender.com"  (Render *.onrender.com domain)
    #   future → "zivabi.com"  (once custom domain is DNS-verified and live)
    # Do NOT set this to "zivabi.com" while the frontend is on onrender.com —
    # the browser rejects rpIds that don't suffix-match the actual origin.
    webauthn_rp_id: str = "localhost"

    # ── Push / VAPID (Phase 3) ────────────────────────────────────────────────
    # Generate keypair once: from pywebpush import Vapid; Vapid().generate_keys()
    # Store in Render dashboard env vars (never commit to repo).
    # If VAPID_PRIVATE_KEY is blank, push sends are silently skipped (safe for dev).
    vapid_private_key: str = ""    # base64url-encoded VAPID private key
    vapid_public_key: str = ""     # base64url-encoded VAPID public key (also in frontend)
    vapid_mailto: str = ""         # e.g. "mailto:admin@zivabi.com"

    # ── Redis cache (Performance Audit) ──────────────────────────────────────
    # Optional. When set, enables Redis-backed caching of hot read paths.
    # Set REDIS_URL in Render dashboard (e.g. rediss://...render.com:6379).
    # When not set, all cache operations are no-ops (safe for local dev).
    redis_url: str = ""

    # ── Payment encryption (M-Payment) ───────────────────────────────────────
    # Fernet key used to encrypt Paystack secret keys before storing in DB.
    # Generate once: from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())
    # Store in Render dashboard env vars (PAYMENT_ENCRYPTION_KEY) — never commit.
    # When blank, raw storage is used (only safe for dev; keys are still never logged).
    payment_encryption_key: str = ""

    # ── Platform owner ────────────────────────────────────────────────────────
    # UUID of the PRAD platform owner. When set, this user's impersonation
    # sessions in live environments are unrestricted (no sensitive field masking).
    # If unset, all super admins are treated as non-owner (restricted in live).
    owner_user_id: str | None = None

    @computed_field  # type: ignore[misc]
    @property
    def allowed_origins(self) -> list[str]:
        """Parse ALLOWED_ORIGINS into a list regardless of input format.

        Accepts:
          - JSON array string: '["https://a.com","https://b.com"]'
          - Comma-separated:   'https://a.com,https://b.com'
          - Single URL:        'https://a.com'

        Using a computed_field (rather than a field_validator on a list[str]
        field) prevents pydantic-settings v2 from attempting JSON-parsing at
        the source level before our own parsing logic runs.
        """
        v: Any = self.allowed_origins_raw
        if isinstance(v, list):
            return v
        if isinstance(v, str):
            stripped = v.strip()
            if stripped.startswith("["):
                return json.loads(stripped)
            return [origin.strip() for origin in stripped.split(",") if origin.strip()]
        return [str(v)]


settings = Settings()
